version: '3'
services:
  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE:  backend-fullstack-test
    volumes:
      - ./mongo:/data/db
  mongo-express:
    depends_on:
      - db
    image: mongo-express
    ports:
      - 8080:8083
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USERNAME} 
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=${MONGO_DB_NAME}
    restart: always